spring:
  application:
    name: eureka-server

#server:
#  port: 8761

eureka:
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
  instance:
    hostname: server2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server2:8761/eureka/
